trial_286_initial:
  graph_hidden_size: ['range2', [5, 8]]
  graph_layer_count: ['range', [4, 7]]
  graph_inner_width: ['range2', [6, 9]]
  graph_inner_depth: ['range', [3, 7]]
  fc_excess_layers: ['range', [3, 6]]
  epochs: ['', [700]]
  batch_size: ['', [100, 200, 300, 400, 500, 600]]
  optim: ['', ['adam', 'lion']]
  lr : ['', [
              1.0e-5, 1.5e-5, 2.0e-5, 2.5e-5, 3.0e-5, 3.5e-5,
              1.0e-4, 1.5e-4, 2.0e-4, 2.5e-4, 3.0e-4, 3.5e-4,
              1.0e-6, 1.5e-6, 2.0e-6, 2.5e-6, 3.0e-6, 3.5e-6,
            ]]

  lrs_factor: ['', [0.8]]
  lrs_patience: ['', [10, 15, 20]]
  lrs_threshold: ['', [1.0e-2, 1.0e-3, 1.0e-4]]

  num_samples: 60